### ISSUE TITLE
how can i change the font size?

### ISSUE THREAD

**Issue by Dashu-Xu** [JazzCore/python-pdfkit#99]
thanks for this lib

**Comment by PaperBag42** [comment]
You can write a CSS rule for this:
```css
/* mystyle.css */
body {
    font-size: 40px;
}
```
Then, add `'user-style-sheet': 'mystyle.css'` to your options.

If you're new to CSS, I'd recommend you check out https://www.w3schools.com/css/.
